Fix use-after-free in DBusAddress
Summary:
Sometimes, `DBusAddress.open` spuriously fails with error -111 (`ECONNREFUSED`):

```
In [1]: bus = pystemd.dbuslib.DBusAddress(b"unix:path=/run/user/6986/systemd/private")
In [2]: bus.open()
---------------------------------------------------------------------------
DBusBaseError                             Traceback (most recent call last)
[snip]/pystemd/examples/shell.py in <module>()
----> 1 bus.open()
pystemd/dbuslib.pyx in pystemd.dbuslib.DBus.open()
DBusBaseError: [err -111]: Could not open a bus to DBus
```

This can happen if `address` (given to `DBusAddress.__init__`) is deallocated before calling `DBus.open`. `sd_dbus_set_address` is then given a garbage string, which sometimes contains the intended address but sometimes contains an invalid path (hence `ECONNREFUSED`).

Fix the bug by making `DBusAddress` store a copy of the address instead of storing a non-owning reference.

Reviewed By: aleivag

Differential Revision: D13779096

fbshipit-source-id: deeb0c60ecac601f6df74598e97aab3807d9973a